package Rules;

import com.ns.check.Model.UserDetails;
import com.ns.check.Model.ResultantModel;



global Float ccAmount;
global Float orderAmount;
global ResultantModel rm;



rule "for other values to Assistant Supervisor"
salience 10
when
userSetailObject:UserDetails()
then
    rm.setDistributorId(userSetailObject.getDistributorId());
    rm.setDistributorLevel(userSetailObject.getLevel());
    rm.setSponserLevel(userSetailObject.getSponserid());
 end



     rule "Bonus for assistant supervisor by novus and his downlines"
            salience 1
            activation-group "purchase"
            when
            userDetailObject:UserDetails(level==2 && nextLevel==1)
//            purchaseObject:Purchase()
            then
            System.out.println("He is having 15% Novus profit and 5 % Novus Bonus");

            float novusProfit=(15*orderAmount)/100;
            System.out.println("Novus Profit is -> "+(15*orderAmount)/100);

            float novusBonus=(5*orderAmount)/100;
            System.out.println("Novus Bonus is -> "+(5*orderAmount)/100);
            System.out.println("Novus CC is ->"+ccAmount);
            System.out.println("Non Manager CC->"+ccAmount);
            rm.setNovusProfit(novusProfit);
            rm.setNovusCc(ccAmount);
            rm.setNovusBonus(novusBonus);
            rm.setNonManagerCc(ccAmount);
            rm.print();
        end

        rule "Bonus for assistant supervisor by assist.Supervisor downlines"
            salience 1
            activation-group "purchase"
            when
            userDetailObject:UserDetails(level==2 && nextLevel==2)
//            purchaseObject:Purchase()
            then
            System.out.println("Only case credits");
            System.out.println("Non Mnager CC->"+ccAmount);
            rm.setNonManagerCc(ccAmount);
            rm.print();
        end

        rule "Bonus for assistant supervisor for his self purchase"
                salience 1
                activation-group "purchase"
                when
                userDetailObject:UserDetails(level==2 && nextLevel==0)
//                purchaseObject:Purchase()
                then
                System.out.println("He is having 30%Direct Discount and 5 % personal Discount");
                System.out.println("Personal CC->"+ccAmount);

                float directDiscount=(30*orderAmount)/100;
                System.out.println("Direct Discount Amount is ->"+(30*orderAmount)/100);

                float personalDiscount=(5*orderAmount)/100;
                System.out.println("Personal Discount Amount is ->"+(5*orderAmount)/100);
                rm.setPersonalCc(ccAmount);
                rm.setDirectDiscount(directDiscount);
                rm.setPersonalDiscount(personalDiscount);
                rm.print();

         end
