//        package Rules;
//
//        import com.ns.check.Model.Purchase;
//        import com.ns.check.Model.UserDetails;
//
//        rule "Bonus for  novus by self purchase"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==1 && nextLevel==0)
//        then
//        System.out.println("He is eligible for 15%direct discount");
//        end
//
//          rule "Bonus for Novus by novus and his downlines"
//                salience 1
//                activation-group "purchase"
//                when
//                userDetailObject:UserDetails(level==1 && nextLevel==1)
//                then
//                System.out.println("Only Case Credits");
//                end
//
//        rule "Bonus for assistant supervisor by novus and his downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==2 && nextLevel==1)
//        then
//        System.out.println("He is having 15% Novus profit and 5 % Novus Bonus");
//
//        end
//
//        rule "Bonus for assistant supervisor by assist.Supervisor downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==2 && nextLevel==2)
//        then
//        System.out.println("Only case credits");
//
//        end
//
//        rule "Bonus for assistant supervisor for his self purchase"
//                salience 1
//                activation-group "purchase"
//                when
//                userDetailObject:UserDetails(level==2 && nextLevel==0)
//                then
//                System.out.println("He is having 30%Direct Discount and 5 % personal Discount");
//
//                end
//
//        rule "Bonus for supervisor by supervisor downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==3 && nextLevel==3)
//        then
//        System.out.println("Only Case Credits");
//
//        end
//
//
//        rule "Bonus for supervisor by Asst.supervisor downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==3 && nextLevel==2)
//        then
//        System.out.println("Only 3% of violume Bonus");
//
//        end
//
//        rule "Bonus for supervisor by novus downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==3 && nextLevel==1)
//        then
//        System.out.println("He is having 15% Novus profit and 8 % Novus Bonus");
//
//        end
//
//         rule "Bonus for supervisor for his self purchase"
//                salience 1
//                activation-group "purchase"
//                when
//                userDetailObject:UserDetails(level==3 && nextLevel==0)
//                then
//                System.out.println("He is having 30%Direct Discount and 8 % personal Discount");
//                end
//
//
//
//
//
//        rule "Bonus for Assistent manager by novus and his downlines "
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==4 && nextLevel==1)
//        then
//        System.out.println("He is eligible for 15%direct discount 13% personal discount");
//        end
//
//        rule "Bonus for Assistent manager by asst.superviser downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==4 && nextLevel==2)
//        then
//        System.out.println("8 % volume Bonus");
//        end
//
//        rule "Bonus for Assistent manager by supervisor downlines"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==4&& nextLevel==3 )
//        then
//        System.out.println("5 % volume Bonus");
//        end
//
//        rule "Bonus for Assistent manager by Assistent manager "
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==4 && nextLevel==4 )
//        then
//        System.out.println("Only Case Credits");
//        end
//
//        rule "Bonus for Assistent manager for his self Purchase "
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==4 && nextLevel==0 )
//        then
//        System.out.println("He is having 30%Direct Discount and 13% Personal Discount");
//        end
//
//
//        rule "self purchase by manager"
//        salience 1
//        activation-group "purchase"
//        when
//        userDetailObject:UserDetails(level==5 && nextLevel==0)
//        then
//        System.out.println("He is eligible for 30%direct discount 18% personal discount");
//        end
//
//          rule "Bonus for  manager by manage and his downlines"
//                salience 1
//                activation-group "purchase"
//                when
//                userDetailObject:UserDetails(level==5 && nextLevel==5)
//                then
//                System.out.println("Only Case Credits is available");
//                end
//
//
//
//        rule "Bonus for Manager by Assistant.Manager and his downlines"
//                salience 1
//                activation-group "purchase"
//                when
//                userDetailObject:UserDetails(level==5 && nextLevel==4)
//                then
//                System.out.println("He is eligible for 5% Volume Bonus");
//                end
//
//                 rule "Bonus for Manager by supervisor and his downlines"
//                                salience 1
//                                activation-group "purchase"
//                                when
//                                userDetailObject:UserDetails(level==5 && nextLevel==3)
//                                then
//                                System.out.println("He is eligible for 10% Volume Bonus");
//                                end
//
//                 rule "Bonus for Manager by Assistant.supervisor and his downlines"
//                                salience 1
//                                activation-group "purchase"
//                                when
//                                userDetailObject:UserDetails(level==5 && nextLevel==2)
//                                then
//                                System.out.println("He is eligible for 13% Volume Bonus");
//                                end
//
//                 rule "Bonus for Manager by Novus  and his downlines"
//                                salience 1
//                                activation-group "purchase"
//                                when
//                                userDetailObject:UserDetails(level==5 && nextLevel==1)
//                                then
//                                System.out.println("He is eligible for 15% Novus Bonus 18% Novus profit ");
//
//                                end